name: periodic-cargo-update

on:
  workflow_dispatch:      # Allow triggering through the UI
  schedule:
    - cron: '0 8 * * *'   # Every day at 8am

jobs:
  cargo-update:
    runs-on: ubuntu-latest
    container:
      image: rust:1.74
    steps:
    - uses: actions/checkout@v4
    # Note: `cargo update --workspace` doesn't seem to have any effect.
    - run: cargo update
      working-directory: wasm-node/rust
    - run: cargo update
      working-directory: full-node
    - run: cargo update
      working-directory: fuzz
    - uses: peter-evans/create-pull-request@v5
      with:
        # We use a custom secret (rather than the default GITHUB_TOKEN) so that opening the pull
        # request triggers other actions such as the CI checks. GitHub prevents actions that use
        # GITHUB_TOKEN from triggering further actions, to avoid recursive actions.
        token: ${{ secrets.GH_TOKEN }}
        committer: Smoldot <pierre.krieger1708@gmail.com>
        author: Smoldot <pierre.krieger1708@gmail.com>
        branch: cargo-update
        base: main
        title: Periodic `cargo update`
        body: >
          This automatic pull request runs `cargo update` on the repository.

          Note that merging this pull request will invalidate the build cache of the GitHub Actions
          and thus slow down the continuous integration. While this pull request is opened and
          updated every day, please consider *not* merging it every day.
        commit-message: Periodic `cargo update`
        delete-branch: true
